# -*- coding: utf-8 -*-
"""Credit_Card_Fraud_Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/credit-card-fraud-detection-1f2eda73-65c4-4666-95b1-637d6e63e950.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250301/auto/storage/goog4_request%26X-Goog-Date%3D20250301T084914Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D622cd2f4b978788573314cf9f28844e316aba4208dfdf603928656727d128148ddca40a19fe51d388a011ff4b12825269af57ec041f300e34bc005666b37f919ef5518a59d01e66033548086366946e227b8b44a12cf27cbd203685941651b7e551952b7e353839859ec4335b109ba8d087ca575b9353b9b3225f2c79e943df68cb8ad77e879f46fc9e3773e248eaa5a56f506d9358580070244b696a5a60861625891d6a838b4471864aef75e399a3e0cd37759d56a0dd4ce7a69aca8f0fa408f94bc9e75e775d261db427f91ed246ea5facc66f7db35cd86e1661b1a5049daa2b6df31bad2c92ff0449482eaa11135230c0f199c59d7f79d24c5c8056e87bc
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

"""# 1. Data Analysis
* Basic statistical analysis
* Correlation analysis
* Distribution analysis
* Time-based patterns
* Amount-based patterns
* Feature importance analysis
*
"""

# 1.Basic Data Analysis